<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

        <OutputType>Exe</OutputType>
        <RootNamespace>SampleApp</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Display name -->
        <ApplicationTitle>SampleApp</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.companyname.sampleapp</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
        <WindowsPackageType>None</WindowsPackageType>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4"/>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128"/>

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>
        <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>

<!--    <ItemGroup>-->
<!--        <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.10"/>-->
<!--    </ItemGroup>-->

<!--    <ItemGroup>-->
<!--      <ProjectReference Include="..\OnScreenSizeMarkup.Maui\OnScreenSizeMarkup.Maui.csproj" />-->
<!--    </ItemGroup>-->




    <ItemGroup>
<!--        <PackageReference Include="CardsView.Maui" Version="1.1.0" />-->
        <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.30" />
<!--        <PackageReference Include="Microsoft.Maui.Controls.Maps" Version="9.0.30" />-->
<!--        <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.30" />-->
<!--        <PackageReference Include="akavache" Version="10.1.6" />-->
<!--        <PackageReference Include="CommunityToolkit.Maui" Version="11.0.0" />-->
<!--        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />-->
<!--        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />-->
<!--        <PackageReference Include="PINView.MAUI" Version="1.0.3" />-->
<!--        <PackageReference Include="Plugin.Maui.CalendarStore" Version="3.0.0-preview2" />-->
<!--        <PackageReference Include="Refit" Version="8.0.0" />-->
<!--        <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />-->
<!--        <PackageReference Include="Syncfusion.Maui.Inputs" Version="28.2.3" />-->
<!--        <PackageReference Include="Syncfusion.Maui.Sliders" Version="28.2.3" />-->
<!--        <PackageReference Include="Syncfusion.Maui.ProgressBar" Version="28.2.3" />-->
<!--        <PackageReference Include="OnScreenSizeMarkup.Maui" Version="4.0.1" />-->
<!--        <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.1" />-->
<!--        <PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.116.1" />-->
<!--        <PackageReference Include="Camera.MAUI" Version="1.5.1" />-->
<!--        <PackageReference Include="Shiny.Push" Version="3.3.4" />-->
<!--        <PackageReference Include="Shiny.Jobs" Version="3.3.4" />-->
<!--        <PackageReference Include="Shiny.Locations" Version="3.3.4" />-->
<!--        <PackageReference Include="Shiny.Core" Version="3.3.4" />-->
<!--        <PackageReference Include="Shiny.Hosting.Maui" Version="3.3.4" />-->
<!--        <PackageReference Include="Shiny.Notifications" Version="3.3.4" />-->
<!--        <PackageReference Include="IeuanWalker.Maui.StateButton" Version="1.2.0" />-->
<!--        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />-->
<!--        <PackageReference Include="Humanizer.Core.pt" Version="2.14.1" />-->
<!--        <PackageReference Include="Plugin.Maui.Audio" Version="3.0.1" />-->
<!--        <PackageReference Include="TemplateMAUI" Version="1.1.0" />-->
<!--        <PackageReference Include="ZXing.Net" Version="0.16.10" />-->
    </ItemGroup>

</Project>
